openapi: 3.0.0
info:
  title: Shopping Cart API
  description: |
    Reservation management section of TempleMSA Airlines API.
    Made by the best group in the class.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /reservations/{reservation_id}:
    delete:
      summary: Cancel a reservation
      description: |
        Cancels reservation with specific reservation_id.
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Identifier of reservation
          schema:
            type : string
          example: 577B4ADB-FCB6-43A5-845B-918A952CB9B4
      
      requestBody:
        required: true
        content:
          application/json:
            example: [
              {
                product_id: 14DAFFD0-7E0F-4B28-B7EF-19C6EF45704A,
                quantity: 4,
                customizations: {
                    color: 'blue',
                    sizeObj: {
                      type: 'W',
                      value: 10
                    }
                  }
              },
              {
                product_id: 181BBDA8-030E-407A-8DC4-7F16A05F55FF,
                quantity: 6,
                customizations: {
                    size: 4
                  }
              }
            ]
            schema:
              type: array
              items:
                type: object
                properties:
                  product_id:
                    type: string
                    example: 14DAFFD0-7E0F-4B28-B7EF-19C6EF45704A
                  quantity:
                    type: integer
                    minimum: 1
                    maximum: 12
                    example: 2
                  customizations:
                    type: object
                    example: {
                      color: 'blue',
                      sizeObj: {
                        type: 'W',
                        value: 10
                      }
                    }
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /reservations/{reservation_id}/people/{person_id}:
    get:
      summary: View info for specific person on reservation
      description: |
        Returns information on person based on person_id
        within reservation based on reservation_id.
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Identifier for reservation
          schema:
            type: string
          example: EFED6D5E-9454-4844-B593-F843E98B339C
        - name: person_id
          in: path
          required: true
          description: Identifier for person
          schema:
            type: string
          example: B8C10FF8-C9A8-40DF-B10E-572DACFC1522
      
      