openapi: 3.0.0
info:
  title: TempleMSA Airlines API
  description: |
    Reservation management portion of TempleMSA Airlines API.
    Made by the best group (Group 3) in the class. This subsection
    within the API allows users to cancel a reservation and obtain
    info on specific passengers within a reservation.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /reservations/{reservation_id}:
    delete:
      summary: Cancel a reservation
      description: |
        Cancels reservation with specific reservation_id.
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Identifier of reservation
          schema:
            type : string
          example: 577B4ADB-FCB6-43A5-845B-918A952CB9B4
      responses:
        '200':    # status code
          description: Returns success status and the ID of the deleted reservation
          content:
            application/json:
              schema: 
                type: object
                properties:
                  reservation_id:
                    type: string
                    example: 577B4ADB-FCB6-43A5-845B-918A952CB9B4
        '400':
          description: |
            Returns detailed error explanation in case client submitted invalid
            data to the event store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400s'
        '401':
          description: |
            Returns detailed error explanation in case where user authentication
            is needed to fulfill request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400s'
        '403':
          description: |
            Returns a detailed explanation in case where request is forbidden
            and will not be fulfilled regardless of repeat requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400s'
        '404':
          description: |
            Returns detailed error explanation in case the reservation ID is not
            found on server 
# either already deleted or does not exist to begin with
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400s'
        '409':
          description: |
            Returns deatiled error explanation in case request conflicts with
            current state of resource
# Cases where reservation is too late to refund? or would it be 403?
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400s'
        '500': 
          description: |
            Returns detailed error explanation in case where server was unable
            to fulfill the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500s'
        '503':
          description: |
            Returns detailed error explanation in case where service is temporarily
            unvailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error500s'

  /reservations/{reservation_id}/people/{person_id}:
    get:
      summary: View info for specific passenger on reservation
      description: |
        Returns information on passenger based on person_id
        within reservation based on reservation_id.
      parameters:
        - name: reservation_id
          in: path
          required: true
          description: Identifier for reservation
          schema:
            type: string
          example: 577B4ADB-FCB6-43A5-845B-918A952CB9B4
        - name: person_id
          in: path
          required: true
          description: Identifier for person
          schema:
            type: string
          example: B8C10FF8-C9A8-40DF-B10E-572DACFC1522
      responses:
        '200':    # status code
          description: success returns a user JSON object with information on associated to {person_id}
          content:
            application/json:
              schema: 
                type: object
                items: 
                  type: object
                  properties:
                    reservation_id:
                      type: string
                    person_id:
                      type: string
                    data:
                      type: object
                example:
                  - reservation_id: 14DAFFD0-7E0F-4B28-B7EF-19C6EF45704A
                    person_id: 3A99E447-E820-4F17-9E50-D0C1563B5007
                    data: {
                      "first_name": John,
                      "last_name": Doe,
                      "DOB": 1/1/2000,
                      "baggage_num": 1,
                      "has_allergy": true,
                      "is_handicap": false,
                      "has_support_animal": false
                    }
        '400':
          description: |
            Returns detailed error explanation in case client submitted invalid
            data to the event store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error400s'

components:
  schemas:
    Error400s:
      type: object
      properties:
        error_id:
          type: integer
        description:
          type: string
        details:
          type: string
      example:
        error_id: 2345
        description: |
          "Error occurred due to type of 400 error."
        details: "Specifics: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors"
    Error500s:
      type: object
      properties:
        error_id:
          type: integer
        description:
          type: string
        details:
          type: string
      example:
        error_id: 1234
        description: |
          "Error occurred due to type of 500 error."
        details: "Specifics: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_errors"